/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo.submodule.svc2

class Library {
    val svc1: demo.submodule.svc1.Library = demo.submodule.svc1.Library()

    fun name(): String {
        return "svc2"
    }

    fun hello(message: String): String {
        return "${name()} -> $message"
    }

    fun helloSvc1(): String {
        return svc1.hello(name())
    }
}
